### ISSUE TITLE
socket error:error: (10038, '')

### ISSUE THREAD

**Issue by morningsky** [venthur/python-ardrone#11]
Can you help me? When I run the demo.py, it's seems can't connect the network.

> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "D:\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "E:\Python\python-ardrone-master\arnetwork.py", line 105, in run
>     inputready, outputready, exceptready = select.select([self.drone.video_pipe, self.drone.nav_pipe], [], [], 1)
> error: (10038, '')

**Comment by morningsky** [comment]
@venthur  @mehoskrd

**Comment by ambikaverma** [comment]
I'm getting the same error. 
@morningsky did you find any fix?
