### ISSUE TITLE
error 98: Address already in use

### ISSUE THREAD

**Issue by pythonstarter** [venthur/python-ardrone#6]
Hello,I'm trying to run a drona raspbery pi, but he cannot run application. Writes the error.

Process ARDroneNetworkProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/zilvis/drone/arnetwork.py", line 56, in run
    nav_socket.bind(('', libardrone.ARDRONE_NAVDATA_PORT))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Maybe that will help me?

**Comment by gessha** [comment]
I have the same problem.
